# Generated by Django 4.2.4 on 2024-10-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_ship_date_order_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped_date',
            new_name='ship_date',
        ),
    ]
